///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace w3schools_Oktratas1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the w3schools_Oktratas1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    [RepositoryFolder("8bd8eec5-2bc0-4eef-a791-e35cb03b7c3a")]
    public partial class w3schools_Oktratas1Repository : RepoGenBaseFolder
    {
        static w3schools_Oktratas1Repository instance = new w3schools_Oktratas1Repository();
        w3schools_Oktratas1RepositoryFolders.W3SchoolsOnlineWebTutorialsAppFolder _w3schoolsonlinewebtutorials;
        w3schools_Oktratas1RepositoryFolders.HTMLTutorialGoogleChromeAppFolder _htmltutorialgooglechrome;
        w3schools_Oktratas1RepositoryFolders.TryitEditorV35GoogleChromeAppFolder _tryiteditorv35googlechrome;

        /// <summary>
        /// Gets the singleton class instance representing the w3schools_Oktratas1Repository element repository.
        /// </summary>
        [RepositoryFolder("8bd8eec5-2bc0-4eef-a791-e35cb03b7c3a")]
        public static w3schools_Oktratas1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public w3schools_Oktratas1Repository() 
            : base("w3schools_Oktratas1Repository", "/", null, 0, false, "8bd8eec5-2bc0-4eef-a791-e35cb03b7c3a", ".\\RepositoryImages\\w3schools_Oktratas1Repository8bd8eec5.rximgres")
        {
            _w3schoolsonlinewebtutorials = new w3schools_Oktratas1RepositoryFolders.W3SchoolsOnlineWebTutorialsAppFolder(this);
            _htmltutorialgooglechrome = new w3schools_Oktratas1RepositoryFolders.HTMLTutorialGoogleChromeAppFolder(this);
            _tryiteditorv35googlechrome = new w3schools_Oktratas1RepositoryFolders.TryitEditorV35GoogleChromeAppFolder(this);
        }

#region Variables

        string _varInput = "Proba2";

        /// <summary>
        /// Gets or sets the value of variable varInput.
        /// </summary>
        [TestVariable("1fe4f8c3-0772-4996-b2ed-048d732a9471")]
        public string varInput
        {
            get { return _varInput; }
            set { _varInput = value; }
        }

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8bd8eec5-2bc0-4eef-a791-e35cb03b7c3a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The W3SchoolsOnlineWebTutorials folder.
        /// </summary>
        [RepositoryFolder("2f15ceb6-024f-4e5a-998b-2dd932476a4d")]
        public virtual w3schools_Oktratas1RepositoryFolders.W3SchoolsOnlineWebTutorialsAppFolder W3SchoolsOnlineWebTutorials
        {
            get { return _w3schoolsonlinewebtutorials; }
        }

        /// <summary>
        /// The HTMLTutorialGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("cbafd293-74e0-43f4-9dae-2bde5cd426f2")]
        public virtual w3schools_Oktratas1RepositoryFolders.HTMLTutorialGoogleChromeAppFolder HTMLTutorialGoogleChrome
        {
            get { return _htmltutorialgooglechrome; }
        }

        /// <summary>
        /// The TryitEditorV35GoogleChrome folder.
        /// </summary>
        [RepositoryFolder("85874ef2-c772-4173-858f-9f0743dcf7ac")]
        public virtual w3schools_Oktratas1RepositoryFolders.TryitEditorV35GoogleChromeAppFolder TryitEditorV35GoogleChrome
        {
            get { return _tryiteditorv35googlechrome; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
    public partial class w3schools_Oktratas1RepositoryFolders
    {
        /// <summary>
        /// The W3SchoolsOnlineWebTutorialsAppFolder folder.
        /// </summary>
        [RepositoryFolder("2f15ceb6-024f-4e5a-998b-2dd932476a4d")]
        public partial class W3SchoolsOnlineWebTutorialsAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _w3schoolsInfo;
            RepoItemInfo _learnhtmlInfo;
            RepoItemInfo _html5Info;
            RepoItemInfo _someitagInfo;
            RepoItemInfo _gsciid1Info;
            RepoItemInfo _searchInfo;
            RepoItemInfo _searchw3schoolsInfo;
            RepoItemInfo _atagtutorialInfo;
            RepoItemInfo _cssInfo;
            RepoItemInfo _tryityourselfInfo;
            RepoItemInfo _pagetitleInfo;
            RepoItemInfo _runInfo;
            RepoItemInfo _thisisaheadingInfo;
            RepoItemInfo _probaInfo;
            RepoItemInfo _titleInfo;
            RepoItemInfo _somespantagInfo;

            /// <summary>
            /// Creates a new W3SchoolsOnlineWebTutorials  folder.
            /// </summary>
            public W3SchoolsOnlineWebTutorialsAppFolder(RepoGenBaseFolder parentFolder) :
                    base("W3SchoolsOnlineWebTutorials", "/dom[@domain='www.w3schools.com']", parentFolder, 30000, null, false, "2f15ceb6-024f-4e5a-998b-2dd932476a4d", "")
            {
                _w3schoolsInfo = new RepoItemInfo(this, "W3schools", "body/div[1]/?/?/a[@innertext='w3schools']", 30000, null, "9874e036-df23-4f25-b84b-72ac23960663");
                _learnhtmlInfo = new RepoItemInfo(this, "LearnHTML", ".//nav[#'mySidenav']/?/?/a[@innertext='Learn HTML']", 30000, null, "87b9cdc0-25b5-4848-aa64-8f42542b89c6");
                _html5Info = new RepoItemInfo(this, "HTML5", ".//div[#'main']/h1[@innertext='HTML5']", 30000, null, "d0e445e4-76bb-4903-bcff-d669ec474af7");
                _someitagInfo = new RepoItemInfo(this, "SomeITag", ".//a[@title='Search W3Schools']/i[@innertext='']", 30000, null, "9ce202d1-d0d0-4372-8146-8d3329a54d75");
                _gsciid1Info = new RepoItemInfo(this, "GscIId1", ".//input[#'gsc-i-id1']", 30000, null, "90a6e4cd-22f7-490d-8aa2-89090e5f5e5b");
                _searchInfo = new RepoItemInfo(this, "Search", ".//div[#'___gcse_0']//form[@method='get']/table[1]/?/?/tr/td[2]/input[@title='search']", 30000, null, "7e8703b1-44c2-4a09-8c76-97e13624e86a");
                _searchw3schoolsInfo = new RepoItemInfo(this, "SearchW3Schools", ".//div[#'topnav']//a[@innertext='']", 30000, null, "d339b87a-7491-456b-a30c-37d6b5b40887");
                _atagtutorialInfo = new RepoItemInfo(this, "ATagTutorial", ".//div[#'___gcse_0']/div/div/div[1]/div[6]/div[2]/div/div/div[2]/div[1]/div[1]/?/?/a[@innertext=' Tutorial']", 30000, null, "1d2f77d8-6cae-4f59-9a27-890e936c01c6");
                _cssInfo = new RepoItemInfo(this, "CSS", ".//div[#'main']/h1[@innertext='CSS ']", 30000, null, "7eafe3d8-48a4-4666-bdec-469bce14e323");
                _tryityourselfInfo = new RepoItemInfo(this, "TryItYourself", ".//div[#'main']/?/?/a[@innertext='Try it Yourself »']", 30000, null, "1cc51460-66c9-4fd8-878d-c49ed108a175");
                _pagetitleInfo = new RepoItemInfo(this, "PageTitle", ".//div[#'textareawrapper']/div/div[6]/div[1]/div/div/div/div[5]/pre[4]/?/?/span[@innertext='Page Title']", 30000, null, "2ffef929-8f0a-4430-9c88-5f43b847fd45");
                _runInfo = new RepoItemInfo(this, "Run", "body/div[5]/?/?/button[@innertext='Run »']", 30000, null, "6b7ac203-7a7c-4977-a33d-501a20cc81cd");
                _thisisaheadingInfo = new RepoItemInfo(this, "ThisIsAHeading", ".//div[#'textareawrapper']/div/div[6]/div[1]/div/div/div/div[5]/pre[8]/?/?/span[@innertext='This is a Heading']", 30000, null, "99db2c5a-df32-4f75-b510-350020b6f67c");
                _probaInfo = new RepoItemInfo(this, "Proba", ".//iframe[#'iframeResult']/?/?/h1[@innertext=$varInput]", 30000, null, "916dd1e0-f595-4c62-af37-651ac1899c3e");
                _titleInfo = new RepoItemInfo(this, "Title", ".//div[#'textareawrapper']/div/div[6]/div[1]/div/div/div/div[5]/pre[4]/span/span[2]", 30000, null, "ecac65de-8310-4cdc-9b11-714bba691ae3");
                _somespantagInfo = new RepoItemInfo(this, "SomeSpanTag", ".//div[#'textareawrapper']/div/div[6]/div[1]/div/div/div/div[5]/pre[8]/span/span[3]", 30000, null, "7e46299e-ac71-448a-84ab-f87aad62b27d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2f15ceb6-024f-4e5a-998b-2dd932476a4d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2f15ceb6-024f-4e5a-998b-2dd932476a4d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The W3schools item.
            /// </summary>
            [RepositoryItem("9874e036-df23-4f25-b84b-72ac23960663")]
            public virtual Ranorex.ATag W3schools
            {
                get
                {
                    return _w3schoolsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The W3schools item info.
            /// </summary>
            [RepositoryItemInfo("9874e036-df23-4f25-b84b-72ac23960663")]
            public virtual RepoItemInfo W3schoolsInfo
            {
                get
                {
                    return _w3schoolsInfo;
                }
            }

            /// <summary>
            /// The LearnHTML item.
            /// </summary>
            [RepositoryItem("87b9cdc0-25b5-4848-aa64-8f42542b89c6")]
            public virtual Ranorex.ATag LearnHTML
            {
                get
                {
                    return _learnhtmlInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LearnHTML item info.
            /// </summary>
            [RepositoryItemInfo("87b9cdc0-25b5-4848-aa64-8f42542b89c6")]
            public virtual RepoItemInfo LearnHTMLInfo
            {
                get
                {
                    return _learnhtmlInfo;
                }
            }

            /// <summary>
            /// The HTML5 item.
            /// </summary>
            [RepositoryItem("d0e445e4-76bb-4903-bcff-d669ec474af7")]
            public virtual Ranorex.H1Tag HTML5
            {
                get
                {
                    return _html5Info.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The HTML5 item info.
            /// </summary>
            [RepositoryItemInfo("d0e445e4-76bb-4903-bcff-d669ec474af7")]
            public virtual RepoItemInfo HTML5Info
            {
                get
                {
                    return _html5Info;
                }
            }

            /// <summary>
            /// The SomeITag item.
            /// </summary>
            [RepositoryItem("9ce202d1-d0d0-4372-8146-8d3329a54d75")]
            public virtual Ranorex.ITag SomeITag
            {
                get
                {
                    return _someitagInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The SomeITag item info.
            /// </summary>
            [RepositoryItemInfo("9ce202d1-d0d0-4372-8146-8d3329a54d75")]
            public virtual RepoItemInfo SomeITagInfo
            {
                get
                {
                    return _someitagInfo;
                }
            }

            /// <summary>
            /// The GscIId1 item.
            /// </summary>
            [RepositoryItem("90a6e4cd-22f7-490d-8aa2-89090e5f5e5b")]
            public virtual Ranorex.InputTag GscIId1
            {
                get
                {
                    return _gsciid1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The GscIId1 item info.
            /// </summary>
            [RepositoryItemInfo("90a6e4cd-22f7-490d-8aa2-89090e5f5e5b")]
            public virtual RepoItemInfo GscIId1Info
            {
                get
                {
                    return _gsciid1Info;
                }
            }

            /// <summary>
            /// The Search item.
            /// </summary>
            [RepositoryItem("7e8703b1-44c2-4a09-8c76-97e13624e86a")]
            public virtual Ranorex.InputTag Search
            {
                get
                {
                    return _searchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Search item info.
            /// </summary>
            [RepositoryItemInfo("7e8703b1-44c2-4a09-8c76-97e13624e86a")]
            public virtual RepoItemInfo SearchInfo
            {
                get
                {
                    return _searchInfo;
                }
            }

            /// <summary>
            /// The SearchW3Schools item.
            /// </summary>
            [RepositoryItem("d339b87a-7491-456b-a30c-37d6b5b40887")]
            public virtual Ranorex.ATag SearchW3Schools
            {
                get
                {
                    return _searchw3schoolsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SearchW3Schools item info.
            /// </summary>
            [RepositoryItemInfo("d339b87a-7491-456b-a30c-37d6b5b40887")]
            public virtual RepoItemInfo SearchW3SchoolsInfo
            {
                get
                {
                    return _searchw3schoolsInfo;
                }
            }

            /// <summary>
            /// The ATagTutorial item.
            /// </summary>
            [RepositoryItem("1d2f77d8-6cae-4f59-9a27-890e936c01c6")]
            public virtual Ranorex.ATag ATagTutorial
            {
                get
                {
                    return _atagtutorialInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ATagTutorial item info.
            /// </summary>
            [RepositoryItemInfo("1d2f77d8-6cae-4f59-9a27-890e936c01c6")]
            public virtual RepoItemInfo ATagTutorialInfo
            {
                get
                {
                    return _atagtutorialInfo;
                }
            }

            /// <summary>
            /// The CSS item.
            /// </summary>
            [RepositoryItem("7eafe3d8-48a4-4666-bdec-469bce14e323")]
            public virtual Ranorex.H1Tag CSS
            {
                get
                {
                    return _cssInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The CSS item info.
            /// </summary>
            [RepositoryItemInfo("7eafe3d8-48a4-4666-bdec-469bce14e323")]
            public virtual RepoItemInfo CSSInfo
            {
                get
                {
                    return _cssInfo;
                }
            }

            /// <summary>
            /// The TryItYourself item.
            /// </summary>
            [RepositoryItem("1cc51460-66c9-4fd8-878d-c49ed108a175")]
            public virtual Ranorex.ATag TryItYourself
            {
                get
                {
                    return _tryityourselfInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The TryItYourself item info.
            /// </summary>
            [RepositoryItemInfo("1cc51460-66c9-4fd8-878d-c49ed108a175")]
            public virtual RepoItemInfo TryItYourselfInfo
            {
                get
                {
                    return _tryityourselfInfo;
                }
            }

            /// <summary>
            /// The PageTitle item.
            /// </summary>
            [RepositoryItem("2ffef929-8f0a-4430-9c88-5f43b847fd45")]
            public virtual Ranorex.SpanTag PageTitle
            {
                get
                {
                    return _pagetitleInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The PageTitle item info.
            /// </summary>
            [RepositoryItemInfo("2ffef929-8f0a-4430-9c88-5f43b847fd45")]
            public virtual RepoItemInfo PageTitleInfo
            {
                get
                {
                    return _pagetitleInfo;
                }
            }

            /// <summary>
            /// The Run item.
            /// </summary>
            [RepositoryItem("6b7ac203-7a7c-4977-a33d-501a20cc81cd")]
            public virtual Ranorex.ButtonTag Run
            {
                get
                {
                    return _runInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Run item info.
            /// </summary>
            [RepositoryItemInfo("6b7ac203-7a7c-4977-a33d-501a20cc81cd")]
            public virtual RepoItemInfo RunInfo
            {
                get
                {
                    return _runInfo;
                }
            }

            /// <summary>
            /// The ThisIsAHeading item.
            /// </summary>
            [RepositoryItem("99db2c5a-df32-4f75-b510-350020b6f67c")]
            public virtual Ranorex.SpanTag ThisIsAHeading
            {
                get
                {
                    return _thisisaheadingInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The ThisIsAHeading item info.
            /// </summary>
            [RepositoryItemInfo("99db2c5a-df32-4f75-b510-350020b6f67c")]
            public virtual RepoItemInfo ThisIsAHeadingInfo
            {
                get
                {
                    return _thisisaheadingInfo;
                }
            }

            /// <summary>
            /// The Proba item.
            /// </summary>
            [RepositoryItem("916dd1e0-f595-4c62-af37-651ac1899c3e")]
            public virtual Ranorex.H1Tag Proba
            {
                get
                {
                    return _probaInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The Proba item info.
            /// </summary>
            [RepositoryItemInfo("916dd1e0-f595-4c62-af37-651ac1899c3e")]
            public virtual RepoItemInfo ProbaInfo
            {
                get
                {
                    return _probaInfo;
                }
            }

            /// <summary>
            /// The Title item.
            /// </summary>
            [RepositoryItem("ecac65de-8310-4cdc-9b11-714bba691ae3")]
            public virtual Ranorex.SpanTag Title
            {
                get
                {
                    return _titleInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Title item info.
            /// </summary>
            [RepositoryItemInfo("ecac65de-8310-4cdc-9b11-714bba691ae3")]
            public virtual RepoItemInfo TitleInfo
            {
                get
                {
                    return _titleInfo;
                }
            }

            /// <summary>
            /// The SomeSpanTag item.
            /// </summary>
            [RepositoryItem("7e46299e-ac71-448a-84ab-f87aad62b27d")]
            public virtual Ranorex.SpanTag SomeSpanTag
            {
                get
                {
                    return _somespantagInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SomeSpanTag item info.
            /// </summary>
            [RepositoryItemInfo("7e46299e-ac71-448a-84ab-f87aad62b27d")]
            public virtual RepoItemInfo SomeSpanTagInfo
            {
                get
                {
                    return _somespantagInfo;
                }
            }
        }

        /// <summary>
        /// The HTMLTutorialGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("cbafd293-74e0-43f4-9dae-2bde5cd426f2")]
        public partial class HTMLTutorialGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _clientInfo;

            /// <summary>
            /// Creates a new HTMLTutorialGoogleChrome  folder.
            /// </summary>
            public HTMLTutorialGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HTMLTutorialGoogleChrome", "/form[@title~'^HTML\\ Tutorial\\ -\\ Google\\ Ch']", parentFolder, 30000, null, true, "cbafd293-74e0-43f4-9dae-2bde5cd426f2", "")
            {
                _clientInfo = new RepoItemInfo(this, "Client", "container[@accessiblename='Google Chrome']/container[2]/container[2]", 30000, null, "846747d0-3917-4234-9f5d-55d1291693d3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("cbafd293-74e0-43f4-9dae-2bde5cd426f2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("cbafd293-74e0-43f4-9dae-2bde5cd426f2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Client item.
            /// </summary>
            [RepositoryItem("846747d0-3917-4234-9f5d-55d1291693d3")]
            public virtual Ranorex.Container Client
            {
                get
                {
                    return _clientInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Client item info.
            /// </summary>
            [RepositoryItemInfo("846747d0-3917-4234-9f5d-55d1291693d3")]
            public virtual RepoItemInfo ClientInfo
            {
                get
                {
                    return _clientInfo;
                }
            }
        }

        /// <summary>
        /// The TryitEditorV35GoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("85874ef2-c772-4173-858f-9f0743dcf7ac")]
        public partial class TryitEditorV35GoogleChromeAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new TryitEditorV35GoogleChrome  folder.
            /// </summary>
            public TryitEditorV35GoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("TryitEditorV35GoogleChrome", "/form[@title~'^Tryit\\ Editor\\ v3\\.5\\ -\\ Googl']", parentFolder, 30000, null, true, "85874ef2-c772-4173-858f-9f0743dcf7ac", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("85874ef2-c772-4173-858f-9f0743dcf7ac")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("85874ef2-c772-4173-858f-9f0743dcf7ac")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}