///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace w3schools_Oktratas1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The writesAndCheck recording.
    /// </summary>
    [TestModule("082c774f-6bc4-4635-a05b-1ace50deeb60", ModuleType.Recording, 1)]
    public partial class writesAndCheck : ITestModule
    {
        /// <summary>
        /// Holds an instance of the w3schools_Oktratas1Repository repository.
        /// </summary>
        public static w3schools_Oktratas1Repository repo = w3schools_Oktratas1Repository.Instance;

        static writesAndCheck instance = new writesAndCheck();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public writesAndCheck()
        {
            varInput = "Proba2";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static writesAndCheck Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable varInput.
        /// </summary>
        [TestVariable("d7f53c95-a2e9-49bc-b1a0-ab5e78520a4f")]
        public string varInput
        {
            get { return repo.varInput; }
            set { repo.varInput = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='HTML5') on item 'W3SchoolsOnlineWebTutorials.HTML5'.", repo.W3SchoolsOnlineWebTutorials.HTML5Info, new RecordItemIndex(0));
            Validate.Attribute(repo.W3SchoolsOnlineWebTutorials.HTML5Info, "InnerText", "HTML5");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'W3SchoolsOnlineWebTutorials.TryItYourself' at 94;20.", repo.W3SchoolsOnlineWebTutorials.TryItYourselfInfo, new RecordItemIndex(1));
            repo.W3SchoolsOnlineWebTutorials.TryItYourself.Click("94;20");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'W3SchoolsOnlineWebTutorials.ThisIsAHeading' at 170;8.", repo.W3SchoolsOnlineWebTutorials.ThisIsAHeadingInfo, new RecordItemIndex(2));
            //repo.W3SchoolsOnlineWebTutorials.ThisIsAHeading.Click("170;8");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'W3SchoolsOnlineWebTutorials.SomeSpanTag' at 5;9.", repo.W3SchoolsOnlineWebTutorials.SomeSpanTagInfo, new RecordItemIndex(3));
            repo.W3SchoolsOnlineWebTutorials.SomeSpanTag.Click("5;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Right}{LShiftKey down}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{LShiftKey up}{Delete}'.", new RecordItemIndex(4));
            Keyboard.Press("{Right}{LShiftKey down}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{Right}{LShiftKey up}{Delete}");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back 9}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Delete}'.", new RecordItemIndex(5));
            //Keyboard.Press("{Back 9}{Back}{Back}{Back}{Back}{Back}{Back}{Back}{Delete}");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$varInput'.", new RecordItemIndex(6));
            Keyboard.Press(varInput);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'W3SchoolsOnlineWebTutorials.Run' at 59;30.", repo.W3SchoolsOnlineWebTutorials.RunInfo, new RecordItemIndex(7));
            repo.W3SchoolsOnlineWebTutorials.Run.Click("59;30");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText=$varInput) on item 'W3SchoolsOnlineWebTutorials.Proba'.", repo.W3SchoolsOnlineWebTutorials.ProbaInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.W3SchoolsOnlineWebTutorials.ProbaInfo, "InnerText", varInput);
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HTMLTutorialGoogleChrome.Client' at 1432;11.", repo.HTMLTutorialGoogleChrome.ClientInfo, new RecordItemIndex(9));
            //repo.HTMLTutorialGoogleChrome.Client.Click("1432;11");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'TryitEditorV35GoogleChrome' at 1812;29.", repo.TryitEditorV35GoogleChrome.SelfInfo, new RecordItemIndex(10));
            repo.TryitEditorV35GoogleChrome.Self.Click("1812;29");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
